<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="MARUDHAR/KANCHAN">

		<title>PMSSS J&K Scholarship</title>

		<!-- Bootstrap Core CSS -->
		<link href="css/bootstrap.min.css" rel="stylesheet">

		<!-- Bootstrap Table CSS -->
		<link href="css/bootstrap-table.min.css" rel="stylesheet" >
		
		<!-- Bootstrap Date Picker CSS -->
		<!--<link href="css/bootstrap-datetimepicker.min.css" rel="stylesheet">-->
		
		<!-- Custom Fonts -->
		<link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		
		<link href="css/style.css" rel="stylesheet" type="text/css">
		
	</head>
<body>
<div id="header" class="navbar navbar-default navbar-fixed-top">
			<div class="navbar-header">
				<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
					<i class="fa fa-bars"></i>
				</button>
				
				<a class="navbar-brand" style="align:center">
					<i class="fa fa-graduation-cap fa-lg"></i>PMSSS J&K Scholarships
				</a>
			</div>
			<!--<nav class="collapse navbar-collapse">
				
				<ul class="nav navbar-nav pull-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<i class="fa fa-user fa-lg"></i> <?php echo $_SESSION['rifdId']; ?><b class="caret"></b></a>
						<ul class="dropdown-menu pull-right">
									<li><a href="Profile.php"><i class="fa fa-user fa-fw"></i> Profile</a></li>
									<li class="divider"></li>
									<li><a href="../session/auth.php?do=logout"><i class="fa fa-power-off"></i> Logout</a></li>
						</ul>
					</li>
				</ul>

			</nav>-->
		</div>
	
 	<h3 class="container" align="center">
					
					  Details of Annexure Downloaded
        </h3>
	<div class="container" id="tableContent">
	<table id="annexure" data-height="430" data-toggle="table" data-url="operations/annexure.php" data-pagination="true" data-search="true" data-sort-name="Batch" data-sort-order="asc" data-show-refresh="true" >
	
		<thead class="btn-primary" >
			
						
						<th data-field="Batch">Batch Number</th>
						<th data-field="Name" data-sortable="true">File Name</th>						
						<th data-field="GeneratedBy">Generated By</th>
						<th data-field="GeneratedOn">Generated On</th>					
						<th data-field="Path" data-visible="false">Path</th>					
						<th data-field="download_annexure" data-formatter="annexure" data-events="operateEvents">Download</th>
				
		</thead>
	</table>

	</div>
</body>
   <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/bootstrap-table.js"></script>
	
	
<script>	
	function annexure(value, row, index) {
		return [
			'&nbsp;&nbsp;&nbsp<a class="downloadannexure ml10" href="javascript:void(0)"  align="center" title="Download Annexure">',
				'<i class="fa fa-download"></i>',
			'</a>&nbsp;'
		].join('');
	}
		
	window.operateEvents = {		
		'click .downloadannexure': function (e, value, row, index) {
			window.location = "../jk_media/"+row.Path;			
		}
		
	};	
	
	
</script>
</html>
  