<?php

session_start();
include("db_connect.php");

// fetching Student ID from session or URL
/* if(isset($_GET['candidateID'])){
  $studentUniqueId=htmlspecialchars($_GET['candidateID']);
  }else{
  $studentUniqueId=$_SESSION['studentUniqueId'];
  } */

// if ($_SESSION['studentUniqueId'] == $_GET['candidateID']) {
//     $studentUniqueId = $_SESSION['studentUniqueId'];
// } else {
//     $_SESSION = array();
//     session_destroy();
//     header('Location: login.php');
// }

$studentUniqueId = $_SESSION['studentUniqueId'];
// fetching Student ID from session
//$studentUniqueId=$_GET['candidateID'];
// $query='SELECT * FROM students WHERE studentUniqueId="'.$studentUniqueId.'"';
// $result = mysqli_query($con,$query);
// $user_row = mysqli_fetch_array($result);

$query = "select * from students where studentUniqueId=? "; //i-int,d-double, s-string,b-blob
$stmt = mysqli_prepare($con, $query);
mysqli_stmt_bind_param($stmt, 'i', $studentUniqueId);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);
$user_row = mysqli_fetch_array($result, MYSQLI_ASSOC);

$query1 = "select * from students_x where studentUniqueId=? "; //i-int,d-double, s-string,b-blob
$stmt1 = mysqli_prepare($con, $query1);
mysqli_stmt_bind_param($stmt1, 'i', $studentUniqueId);
mysqli_stmt_execute($stmt1);
$result1 = mysqli_stmt_get_result($stmt1);
$user_row_x = mysqli_fetch_array($result1, MYSQLI_ASSOC);

if ($user_row['title'] == 'Diploma') {
    $RollNo = $user_row['XIINewRollNo'];
    $CollegeCaption = "Diploma College Details (10+3)<sup>th</sup>";
    $CollegeNameCaption = 'Name of the College';
    $CollegeAddressCaption = 'Address of the College';
} else {
    $RollNo = $user_row['XIIRollNo'];
    $CollegeCaption = "Higher Secondary School (10+2)<sup>th</sup>";
    $CollegeNameCaption = 'Name of the School';
    $CollegeAddressCaption = 'Address of the School';
}
//convert date format of database to d-m-Y
$originalDate = $user_row['birthDate'];
$birthdate = date("d-m-Y", strtotime($originalDate));


$markingType = $user_row['markSystemType'];
if ($markingType == 'Marking System') {
    $rowmarking = '<tr>
							<td width="22%" align="left" bgcolor="#99CCFF"><b>Marks Obtained:</b></td>
							<td width="22%" align="left">' . $user_row['XMarksObtained'] . '</td>
							<td width="22%" align="left" bgcolor="#99CCFF"><b>Total Marks:</b></td>
							<td width="22%" align="left">' . $user_row['XTotalMarks'] . '</td>
						</tr>
						<tr>
							<td width="22%" align="left" bgcolor="#99CCFF"><b>Percentage:</b></td>
							<td width="22%" align="left">' . $user_row['XPercentage'] . '</td>
							<td width="22%" align="left" bgcolor="#99CCFF"><b>Division:</b></td>
							<td width="22%" align="left">' . $user_row['XDivision'] . '</td>
						</tr>';
    //echo $rowmarking;
} else if ($markingType == 'Grading System') {
    $rowgrading = '<tr>
							<td width="22%" align="left" bgcolor="#99CCFF"><b>Grade (as per 10th Marksheet):</b></td>
							<td width="22%" align="left">' . $user_row['XGrade'] . '</td>
							<td width="22%" align="left" bgcolor="#99CCFF"><b>Grade Point (as per 10th Marksheet):</b></td>
							<td width="22%" align="left">' . $user_row['XGradePoint'] . '</td>
						</tr>';
    //echo $rowgrading;
}

mysqli_close($con);
$html = '
	<!DOCTYPE HTML>
	<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
	<link rel="stylesheet" type="text/css" href="css/style_applicationForm.css">

	</head>
	<body style="background-image: url(img/bckimg.jpg); background-image-resize:4;background-repeat: no-repeat; ">
	<htmlpagefooter name="footer">
	<table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt; 
		color: #000000; font-weight: bold; font-style: italic;"><tr>
		<td width="33%"><span style="font-weight: bold; font-style: italic;">' . $user_row['submissionDate'] . '</span></td>
		<td width="33%"><span style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Generated by Student</span></td>
		<td width="33%" align="right" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
	   
		</tr></table>
	</htmlpagefooter>


	<sethtmlpagefooter name="footer" value="on" />



	<htmlpageheader name="header">
	<table border="0" cellspacing="0" cellpadding="0" width="100%" bgcolor="#D7E1EF">
		<tbody>
			<tr>
				<td valign="top" width="5%" >
				 <img src="img/emblem.jpg" alt="Aicte Logo" class="image" align="left">
				</image>
				</td>
				 <td valign="top" width="90%" align="center">
				 <font face="Times New Roman">
					<p align="center" style="font-size:12px">
						<strong>
							ADMISSIONS UNDER PRIME MINISTER’S SPECIAL SCHOLARSHIP SCHEME FOR STUDENTS BELONGING TO JAMMU,  KASHMIR AND LADAKH STATE '.FINANCIAL_YEAR.' IMPLEMENTED BY
						</strong>
					 </p>
					<p align="center" style="font-size:12px">
					  
						<strong>ALL INDIA COUNCIL FOR TECHNICAL EDUCATION, NEW DELHI </strong>
					</p>
					</font>
					<font face="Times New Roman" >
					<p align="center" style="font-size:9px" >
						(AS PER DIRECTIVES OF MINISTRY OF HUMAN RESOURCE DEVELOPMENT, GOVT. OF INDIA, NEW DELHI)
					
					</p>
					</font>
				</td>
				<td valign="top" width="5%">
					<img src="img/logo_doc.jpg" alt="Aicte Logo" class="image" align="right">
				</image>
				</td>
			</tr>
		</tbody>
	</table>
	<br></br>

	<br></br>
	</htmlpageheader>



	<sethtmlpageheader name="header" page="O" value="on" show-this-page="1" />
	<sethtmlpageheader name="header" page="E" value="on" />


	<br></br>
	<br></br>
	<table cellspacing="1" cellpadding="2" border="1" width="20%" align="center">
		<tbody>
			<tr>
				<td align="center" width="100%">
					<div class="box">
						<p>
							<strong><u>Application Form</u></strong>
							</p>
					</div>
				</td>
			</tr>
		</tbody>
	</table>



	 
	 
	 
	 
	 
	 

	<br></br>



	<div class="tableheading">

	  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Personal Details of Applicant:

	</div>



	<table border="1" cellspacing="5" cellpadding="3" width="88%" align="center">

			<tr>
				<td valign="top" width="20%" bgcolor="#99CCFF">
					<p>
						<strong>Candidate Id:</strong>
					</p>
				</td>
				<td valign="top" width="20%">
				<p>
					  ' . $user_row['studentUniqueId'] . '
					</p>
				</td>
				<td valign="top" rowspan="7" width="15%">
				<img src="/jk_media/' . $user_row['photo'] . '" width="110" height="140">	
					
				</td>
				<td valign="top" rowspan="7" width="15%">
				<img src="/jk_media/' . $user_row_x['fatherPhoto'] . '" width="110" height="140">
				</td>
				<td valign="top" rowspan="7" width="15%">
				<img src="/jk_media/' . $user_row_x['motherPhoto'] . '" width="110" height="140">
				</td>
				
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Name of the candidate:</strong>
					</p>
				</td>
				<td valign="top" >
					<p>
							' . $user_row['name'] . '
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Gender:</strong>
					</p>
				</td>
				<td valign="top">
					<p>
					   ' . $user_row['gender'] . '
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Whether Domicile of J&amp;K?:</strong>
					</p>
				</td>
				<td valign="top">
					<p>
						' . $user_row['isDomicileJK'] . '
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Date of birth:</strong>
					</p>
				</td>
				<td valign="top">
					<p>
						
						' . $birthdate . '
						
					</p>
				</td>
			</tr>
			
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Caste Category:</strong>
					</p>
				</td>
				<td valign="top" >
					<p>
					   ' . $user_row['casteCategory'] . '
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Sub Category:</strong>
					</p>
				</td>
				<td valign="top">
					<p>
						' . $user_row['subCasteCategory'] . '
					</p>
				</td>
			</tr>
			
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Physically Disability:</strong>
					</p>
				</td>
				<td valign="top">
					<p>
						' . $user_row['isPhysicallyDisabled'] . '
					</p>
				</td>
				<td valign="top" rowspan="2" width="20%">
				<img src="/jk_media/' . $user_row['signature'] . '" width="110" height="40">
				 				
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Aadhar Details (UID):</strong>
					</p>
				</td>
				<td valign="top">
					<p>
						' . $user_row['UIDNo'] . '
					</p>
				</td>
			</tr>

	</table>


	<br></br>

	<div class="tableheading">

		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Family/Income Details:

	</div>


				   
	<table border="1" cellspacing="5" cellpadding="3" width="88%" align="center">
		<tbody>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Name of the Father/Guardian:</strong>
					</p>
				</td>
				<td valign="top" width="26%">
				
					   ' . $user_row['fatherName'] . '
				</td>
				<td valign="top" width="19%" bgcolor="#99CCFF">
					<p>
						<strong>Name of the Mother/Guardian:</strong>
					</p>
				</td>
				<td valign="top" width="28%">
				
				' . $user_row['motherName'] . '
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Occupation:</strong>
					</p>
				</td>
				<td valign="top" width="26%">
				
				  ' . $user_row['fatherOccupation'] . '
				</td>
				<td valign="top" width="19%" bgcolor="#99CCFF">
					<p>
						<strong>Occupation:</strong>
					</p>
				</td>
				<td valign="top" width="28%">
				  ' . $user_row['motherOccupation'] . '
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Designation:</strong>
					</p>
				</td>
				<td valign="top" width="26%">
				
				   ' . $user_row['fatherDesignation'] . '
				</td>
				<td valign="top" width="19%" bgcolor="#99CCFF">
					<p>
						<strong>Designation:</strong>
					</p>
				</td>
				<td valign="top" width="28%">
					' . $user_row['motherDesignation'] . '
				</td>
			</tr>
			
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Mobile Number:</strong>
					</p>
				</td>
				<td valign="top" width="26%">
				' . $user_row['fatherMobile'] . '
				</td>
				<td valign="top" width="19%"  bgcolor="#99CCFF">
					<p>
						<strong>Mobile Number:</strong>
					</p>
				</td>
				<td valign="top" width="28%">
					<p>
					  ' . $user_row['motherMobile'] . '
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Family Annual Income:</strong>
					</p>
				</td>
				<td valign="top" width="75%" colspan="3">
					<p>
						 ' . $user_row['familyIncome'] . '
					</p>
				</td>
			</tr>
		</tbody>
	</table>


	<br></br>
	<!--<div class="tableheading">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Address Details:
	</div>   
	<table border="1" cellspacing="5" cellpadding="3" width="88%" align="center">
		<tbody>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Mobile Number:</strong>
					</p>
				</td>
				<td valign="top" width="72%" colspan="3">
					<p>
						' . $user_row['mobileNo'] . ', ' . $user_row['alternateMobileNo'] . ' ,' . $user_row['landlineStdCode'] . '-' . $user_row['landlineNumber'] . '
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Email Address:</strong>
					</p>
				</td>
				<td valign="top" width="72%" colspan="3">
					<p>
					   ' . $user_row['primaryEmailId'] . '
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="24%" bgcolor="#99CCFF">
					<p>
						<strong>Permanent Address:</strong>
					</p>
				</td>
				<td valign="top" width="26%">
					<p>
						' . $user_row['permanentAddress'] . ',
					
					
						' . $user_row['permanentCity'] . ',
					
					   ' . $user_row['permanentDistrict'] . ',
					
						' . $user_row['permanentState'] . ',
					
						' . $user_row['permanentPinCode'] . '
					</p>
				</td>
				<td valign="top" width="19%" bgcolor="#99CCFF">
					<p>
						<strong>Current Address:</strong>
					</p>
				</td>
				<td valign="top" width="28%">
				   
						' . $user_row['currentAddress'] . ',
					
						' . $user_row['currentCity'] . ',
				   
						' . $user_row['currentDistrict'] . ',
					
						' . $user_row['currentState'] . ',
				   
					   ' . $user_row['currentPincode'] . '
				  
				</td>
			</tr>
		</tbody>
	</table>-->

	<br></br>
	<div class="tableheading">

		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Educational Details:

	</div>
				   
	<table border="1" cellspacing="5" cellpadding="3" width="88%" align="center">
		<tbody>
			<tr>
				<td valign="top" width="100%" colspan="4" align="center" bgcolor="#99CCFF">
					<p>
						<strong>' . $CollegeCaption . '</strong>
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>Stream</strong>
					</p>
				</td>
				<td valign="top" width="22%">
					<p>
					   ' . $user_row['XIIStream'] . '
					</p>
				</td>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>Other Stream (if any):</strong>
					</p>
				</td>
				<td valign="top" width="22%">
					<p>
						' . $user_row['XIIOtherStream'] . '
					</p>
				</td>
			</tr>
			
			<tr>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>' . $CollegeNameCaption . ':</strong>
					</p>
				</td>
				<td valign="top" width="22%">
					<p>
					   ' . $user_row['XIISchoolName'] . '
					</p>
				</td>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>' . $CollegeAddressCaption . ':</strong>
					</p>
				</td>
				<td valign="top" width="22%">
					<p>
						' . $user_row['XIISchoolAddress'] . '
					</p>
				</td>
			</tr>
	 
		  
		<tr>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>Name of the Board:</strong>
					</p>
				</td>
				<td valign="top" width="22%">
					<p>
						 ' . $user_row['XIIBoardName'] . '
					</p>
				</td>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>Roll No:</strong>
					</p>
				</td>
				<td valign="top" width="22%">
					<p>
						' . $RollNo . '
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>Year Of Passing:</strong>
					</p>
				</td>
				<td valign="top" colspan="3">
					<p>
						 ' . $user_row['XIIYearOfPassing'] . '
					</p>
				</td>
				
			</tr>
			
			<tr>
				 <td valign="top" width="88%" colspan="4" align="center" bgcolor="#99CCFF">
					<p align="center">
						<strong>Senior Secondary School (10)<sup>th</sup></strong>
					</p>
				</td>
			</tr>
			<tr>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>Marking System:</strong>
					</p>
				</td>
				<td valign="top" width="22%">
					<p>
						' . $user_row['markSystemType'] . '
					</p>
				</td>
				<td valign="top" width="22%" bgcolor="#99CCFF">
					<p>
						<strong>Roll Number: </strong>
					</p>
				</td>
				<td valign="top" width="22%">
					<p>
						' . $user_row['XRollNo'] . '
					</p>
				</td>
			</tr>
			' . $rowmarking . '	' . $rowgrading . '
			
		
		</tbody>
	</table>

<br></br>
<div class="tableheading">
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Additional Details:</strong>
</div>
<table border="1" cellspacing="5" cellpadding="3" width="88%" align="center">
    <tbody>
        <tr><td width="50%" bgcolor="#99CCFF">
                <p>
                    <strong>Application Submission Date</strong>
                </p>
            </td>
            <td width="50%">
			<p align="center">
			' . $user_row['submissionDate'] . '
			</p>
            </td></tr>
			        <tr><td width="50%"  bgcolor="#99CCFF">
                <p>
                    <strong>Current Application Status</strong>
                </p>
            </td>
            <td width="50%">
			<p align="center">
			' . $user_row['applicationStatus'] . '
			</p>
            </td></tr>
		</tbody>
		</table><br></br>
<!--<div class="tableheading">

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Counselling Details:

</div>-->
               
<!--<table border="1" cellspacing="5" cellpadding="3" width="88%" align="center">
    <tbody>
        ';
if ($user_row['XIIStream'] == 'Science') {
    $html .= '<tr>
            <td valign="top" width="22%" bgcolor="#99CCFF" rowspan="2">
                <p>
                    <strong><center>Stream applied for </center></strong>
                </p>
            </td>
            <td valign="top" width="22%" bgcolor="#99CCFF">
                <p>
                     <strong><center>(I)</center></strong>
                </p>
            </td>
        
            <td valign="top" width="23%" bgcolor="#99CCFF">
                <p>
                    <strong><center>(II)</center></strong>
                </p>
            </td>
            <td valign="top" bgcolor="#99CCFF">
                <p>
                     <strong><center>(III)</center></strong>
                </p>
            </td>
        </tr>
		<tr>
            <td valign="top" >
                <p>
                    ' . $user_row['streamAppliedfor'] . '
                </p>
            </td>
            <td valign="top">
                <p>
                     ' . $user_row['streamAppliedForPref2'] . '
                </p>
            </td>
			<td valign="top">
                <p>
                     ' . $user_row['streamAppliedForPref3'] . '
                </p>
            </td>
        </tr>
		 ';
} else {
    $html .= '<tr>
            <td valign="top" width="23%" bgcolor="#99CCFF">
                <p>
                    <strong>Stream applied for:</strong>
                </p>
            </td>
            <td valign="top" colspan="3">
                <p>
                     ' . $user_row['streamAppliedfor'] . '
                </p>
            </td>
        </tr>';
}
$html .= '
		
        <tr>
            <td valign="top" width="23%" bgcolor="#99CCFF">
                <p>
                    <strong>Grievance Centre:</strong>
                </p>
            </td>
            <td valign="top" colspan="3">
                <p>
                    ' . $user_row['counsellingCentre'] . '
                </p>
            </td>
        </tr>
		
    </tbody>
</table>
<br></br><br></br><br></br>-->
<div class="declaration">

<p>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><u>Declaration by the Student:</u></strong>
</p>
<p>
    <strong>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I certify that the information uploaded on in this application is correct to the best of my Knowledge.I understand <br>
	 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;that to falsify information is grounds for refusing the Scholarship to me or for action as per rules decided by  <br>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; AICTE from time to time.
    </strong>
</p>

<div class="end">

	
		<strong>
			' . $user_row['name'] . '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</strong>
	
	<p>
		<strong>
			Signature of the Student &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</strong>
	</p>
	<p>
		--------------------------------------------------------------------------------------------------------------------------------------------------------------&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	</p>
	
</div>
</div>

<div class="instruction">
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <strong><u>Instructions to the Candidates for Document Verification:</u></strong>

</div>



<pre>
<div class="instructiontext">
			1.	Candidate is requested to get his/her documents verified from any of the designated facilitation
			           centre established for admission under J&K Special Scholarship Scheme.
			2.	Please visit  ' . $_SERVER['HTTP_HOST'] . ' to get list of Facilitation Centre.
			3.	Original Documents to be produced at the time of Verification at Facilitation Centre.
					a.	X Standard Marksheet.
					b.	XII Standard Marksheet. 
					c.	Domicile certificate.
					d.	Aadhaar card/Enrollement card.
					e.	Annual Income certificate issued by competent authority showing family income for the financial year 2023-24.
					f.	Valid Caste certificate for SC/ST/OBC Candidates issued by the competent authority(Claiming reservation, 
					           if any).
					g.	Valid disability Certificate for the persons falling under Person with disability(PWD) category(If neccessary).
			4.	 After document verification from the facilitation centre candidate should collect the copy of document verification
				    report without fail & same should be produced at the time of Counseling.
                         -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		        Note: - 
				Candidates should submit one set of Photocopies (Xerox) of all the documents produced at the time of Verification to the Facilitation 
				    Centre.
				Candidate should not submit any Original document at the Facilitation Centre.
		</div>
		</pre>

		</body>
		</html>

		';


include("mpdf60/mpdf.php");
$mpdf = new mPDF();
//$mpdf->SetWatermarkImage('/jk_media/img/bckimg.jpg',0.2,'P');   
//$mpdf->showWatermarkImage = true; 
$mpdf->setAutoTopMargin = 'stretch';
$mpdf->setAutoBottomMargin = 'stretch';
$mpdf->SetHTMLHeaderByName('header',true);
$mpdf->WriteHTML($html);
$mpdf->SetHTMLFooterByName('footer');

//$mpdf->Output();
if (isset($_GET['candidateID'])) {
    $mpdf->Output('Allotment Letter.pdf', 'I');
}
?>  